version: '3.5'
services:
  tomcat1:
      restart: on-failure:3
      build:
        context: .
      image: tomcat:8.5
      environment:
        - PASSWORD=123456
        - TZ=Asia/Shanghai
      volumes:
        #- $PWD/data/tomcat1/webapps:/usr/local/tomcat/webapps
        - $PWD/data/tomcat1/conf:/usr/local/tomcat/conf
        - $PWD/data/tomcat1/logs:/usr/local/tomcat/logs
      tty: true
      container_name: tomcat1
      networks:
        tomcats:
              ipv4_address: 172.102.0.2
              aliases:
                - tomcats1
networks:
  tomcats:
    external: false
    name: tomcats
    ipam:
      config:
        - subnet: 172.102.0.0/24
