version: '3.5'
services:
  tomcat1:
      restart: on-failure
      build:
        context: .
      image: tomcat:8.5
      environment:
        - PASSWORD=123456
        - TZ=Asia/Shanghai
        #volumes:
       # - $PWD/data/tomcat1/webapps:/usr/local/tomcat/webapps
      tty: true
      container_name: tomcat1
      networks:
        - tomcats
      command: catalina.sh run && /bin/sh



networks:
  tomcats:
    external: false
    name: tomcats
