version: '3'
services:
  tomcat1:
      build:
        context: .
      image: tomcat:8.5
      environment:
        - PASSWORD=123456
      #volumes:
       # - $PWD/data/tomcat1/webapps:/usr/local/tomcat/webapps
      tty: true
      container_name: tomcat1
      networks:
        tomcat:
          ipv4_address: 172.102.0.2
          aliases:
            - tomcat1
networks:
  tomcat:
    ipam:
      config:
        - subnet: 172.102.0.0/16
