version: '3.5'
services:
  tomcat1:
      build:
        context: .
      image: tomcat:8.5
      networks:
        - tomcats
      environment:
        - PASSWORD=123456
      #volumes:
       # - $PWD/data/tomcat1/webapps:/usr/local/tomcat/webapps
      tty: true
      container_name: tomcat1
      networks:
        - tomcats
networks:
  tomcats:
    external: true
    name: tomcats
