version: '3.5'
services:
  tomcat1:
      restart: on-failure:3
      build:
        context: .
      image: tomcat:8.5
      environment:
        - PASSWORD=123456
        - TZ=Asia/Shanghai
       volumes:
        - $PWD/data/tomcat1/webapps:/usr/local/tomcat/webapps
      tty: true
      container_name: tomcat1
#      networks:
#        tomcats:
#              ipv4_address: 172.101.0.7
#              aliases:
#                - master6
networks:
  tomcats:
    external: false
    name: tomcats
