version: '3'
services:
  tomcat1:
      build:
        context: .
      image: tomcat:8.5
      environment:
        - PASSWORD=123456
      volumes:
        - $PWD/data/tomcat/app:/usr/local/tomcat/app
      tty: true
      container_name: tomcat1
