version: '3.5'
services:
  tomcat1:
      restart: on-failure:3
      build:
        context: .
      image: tomcat:8.5
      environment:
        - PASSWORD=123456
        - TZ=Asia/Shanghai
      volumes:
        - $PWD/data/tomcat1/webapps:/usr/local/tomcat/webapps
       # - $PWD/data/tomcat1/conf:/usr/local/tomcat/conf
        - $PWD/data/tomcat1/logs:/usr/local/tomcat/logs
      tty: true
      container_name: tomcat1
      hostname: tomcat1
      networks:
        - tomcats
  tomcat2:
      restart: on-failure:3
      image: tomcat:8.5
      environment:
        - PASSWORD=123456
        - TZ=Asia/Shanghai
      volumes:
        - $PWD/data/tomcat2/webapps:/usr/local/tomcat/webapps
        # $PWD/data/tomcat2/conf:/usr/local/tomcat/conf
        - $PWD/data/tomcat2/logs:/usr/local/tomcat/logs
      tty: true
      container_name: tomcat2
      hostname: tomcat2
      networks:
        - tomcats
  tomcat3:
      restart: on-failure:3
      image: tomcat:8.5
      environment:
        - PASSWORD=123456
        - TZ=Asia/Shanghai
      volumes:
        - $PWD/data/tomcat3/webapps:/usr/local/tomcat/webapps
        #- $PWD/data/tomcat3/conf:/usr/local/tomcat/conf
        - $PWD/data/tomcat3/logs:/usr/local/tomcat/logs
      tty: true
      container_name: tomcat3
      hostname: tomcat3
      networks:
        - tomcats
networks:
  tomcats:
    external: true