version: '3.5'
services:
  hadoop:
      build:
        context: .
      image: hadoop:my
      volumes:
        - $PWD/data/hadoop/logs:/home/hadoop/hadoop-3.1.2/logs
      tty: true
      ports:
         - "8088:8088"
         - "8080:8080"
         - "50020:50020"
         - "9000:9000"
      container_name: hadoop
      networks:
          hadoop:
            ipv4_address: 172.102.0.2
            aliases:
              - hadoop
        # hostname: h1
       # environment:
       #     HADOOP_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 0.0.0.0 h1
      privileged: true
      command:   /usr/sbin/init
  hadoop2:
      image: hadoop:my
      volumes:
          - $PWD/data/hadoop/logs:/home/hadoop/hadoop-3.1.2/logs
      tty: true
      networks:
        hadoop:
          ipv4_address: 172.102.0.3
          aliases:
            - hadoop2
      container_name: hadoop2
      privileged: true
      command:   /usr/sbin/init
  hadoop3:
        image: hadoop:my
        volumes:
            - $PWD/data/hadoop/logs:/home/hadoop/hadoop-3.1.2/logs
        tty: true
        networks:
          hadoop:
            ipv4_address: 172.102.0.4
            aliases:
              - hadoop3
        container_name: hadoop3
        privileged: true
        command:   /usr/sbin/init

networks:
  hadoop:
    ipam:
      config:
        - subnet: 172.102.0.0/16
