version: '3.5'
services:
  hadoop:
      build:
        context: .
      image: hadoop:my
      volumes:
        - $PWD/data/hadoop/logs:/data/hadoop/logs
      tty: true
#      ports:
#        - "8088:8088"
#        - "8080:8080"
#        - "50020:50020"
#        - "9000:9000"
      container_name: hadoop
      privileged: true
      command:   /usr/sbin/init
  hadoop2:
      image: hadoop:my
      volumes:
        - $PWD/data/hadoop2/logs:/data/hadoop/logs
      tty: true
      container_name: hadoop2
      privileged: true
      command:   /usr/sbin/init
  hadoop3:
        image: hadoop:my
        volumes:
          - $PWD/data/hadoop3/logs:/data/hadoop/logs
        tty: true
        container_name: hadoop3
        privileged: true
        command:   /usr/sbin/init