version: '3.5'
services:
  hadoop:
      build:
        context: .
      image: hadoop:my
      volumes:
        - $PWD/data/hadoop/logs:/data/hadoop/logs
      tty: true
      ports:
         - "8088:8088"
         - "8080:8080"
         - "50020:50020"
         - "9000:9000"
      container_name: hadoop
      networks:
        hadoop:
          ipv4_address: 172.102.0.1
          aliases:
            - hadoop
      privileged: true
      command:   /usr/sbin/init
  hadoop2:
      image: hadoop:my
      volumes:
        - $PWD/data/hadoop2/logs:/data/hadoop/logs
      tty: true
      networks:
        hadoop:
          ipv4_address: 172.102.0.2
          aliases:
            - hadoop2
      container_name: hadoop2
      privileged: true
      command:   /usr/sbin/init
  hadoop3:
        image: hadoop:my
        volumes:
          - $PWD/data/hadoop3/logs:/data/hadoop/logs
        tty: true
        networks:
          hadoop:
            ipv4_address: 172.102.0.3
            aliases:
              - hadoop3
        container_name: hadoop3
        privileged: true
        command:   /usr/sbin/init

networks:
  hadoop:
    ipam:
      config:
        - subnet: 172.102.0.0/16
