version: '3'
services:
  nginx:
      build:
        context: .
      image: nginx:master
      environment:
        - PASSWORD=123456
      volumes:
        - $PWD/data/nginx:logs
      ports:
        - "80:80"
      tty: true
      container_name: nginx

