version: '3.5'
services:
  nginx:
      build:
        context: .
      image: nginx:master
      environment:
        - PASSWORD=123456
        - TZ=Asia/Shanghai
      volumes:
        - $PWD/data/nginx/logs:/data/nginx/logs
        - $PWD/static:/data/nginx/static
      ports:
        - "80:80"
      networks:
        - tomcats
      tty: true
      container_name: nginx
      command:
        - /bin/sh
        - -c
        - |
          sed -i '2i\ server   tomcat1:8080 weight=1 max_fails=2 fail_timeout=30s; ' /etc/nginx/web1.conf
          sed -i '2i\ server   tomcat2:8080 weight=1 max_fails=2 fail_timeout=30s; ' /etc/nginx/web1.conf
          nginx -g 'daemon off;'
      #links:
      #  - tomcat1:t1
      #depends_on:
      #  - tomcat1

networks:
  tomcats:
    external: true
