version: '3'
services:
  master:
      build:
        context: .
        args:
          password: 123456
      image: redis:master
      environment:
        - PASSWORD=123456
      volumes:
        - $PWD/data/redis/master:/data/redis
      ports:
        - "6378:6379"
      tty: true
      command: redis-server   /redis.conf   --masterauth $PASSWORD --requirepass $PASSWORD
  slave1:
      image: redis:master
      volumes:
         - $PWD/data/redis/slave1:/data/redis
      depends_on:
          - master
      links:
          - master
      command: redis-server   /redis.conf  --slaveof master 6379 --masterauth $PASSWORD --requirepass $PASSWORD
  slave2:
    image: redis:master
    volumes:
      - $PWD/data/redis/slave2:/data/redis
    depends_on:
      - master
    links:
      - master
    command: redis-server   /redis.conf  --slaveof master 6379 --masterauth $PASSWORD --requirepass $PASSWORD
  sentinel1:
      image: redis:master
      volumes:
        - $PWD/data/redis/sentinel1:/data/redis
      ports:
        - "26378:26379"
      tty: true
      command:
        - /bin/sh

      depends_on:
        - master
      links:
        - master
