version: '3'
services:
  master1:
      build:
        context: .
        args:
          cluster: ""  #放开集群注释
      image: redis:cluster
      ports:
        - "6378:6379"
      volumes:
        - $PWD/data/redis/master1:/data/redis
      command: redis-server   /redis.conf   --masterauth $PASSWORD --requirepass $PASSWORD
      deploy:
        mode: replicated
        replicas: 6