version: '3'
services:
  master1:
      build:
        context: .
        args:
          cluster: ""  #放开集群注释
      image: redis:cluster
      container_name: master1
      networks:
        redis:
          ipv4_address: 172.19.0.2
          aliases:
            - master1
      ports:
        - "6378:6379"
      volumes:
        - $PWD/data/redis/master1:/data/redis
      command: redis-server   /redis.conf   --masterauth $PASSWORD --requirepass $PASSWORD
  master2:
    image: redis:cluster
    container_name: master2
    networks:
      redis:
        ipv4_address: 172.19.0.3
        aliases:
          - master2
    ports:
      - "6377:6379"
    volumes:
      - $PWD/data/redis/master2:/data/redis
    command: redis-server   /redis.conf   --masterauth $PASSWORD --requirepass $PASSWORD
  master3:
      image: redis:cluster
      networks:
        redis:
          ipv4_address: 172.19.0.4
          aliases:
            - master3
      container_name: master3
      ports:
        - "6376:6379"
      volumes:
        - $PWD/data/redis/master3:/data/redis
      command: redis-server   /redis.conf   --masterauth $PASSWORD --requirepass $PASSWORD
  master4:
    image: redis:cluster
    networks:
      redis:
        ipv4_address: 172.19.0.5
        aliases:
          - master4
    container_name: master4
    ports:
      - "6375:6379"
    volumes:
      - $PWD/data/redis/master4:/data/redis
    command: redis-server   /redis.conf   --masterauth $PASSWORD --requirepass $PASSWORD
  master5:
    image: redis:cluster
    networks:
      redis:
        ipv4_address: 172.19.0.6
        aliases:
          - master5
    container_name: master5
    ports:
      - "6374:6379"
    volumes:
      - $PWD/data/redis/master5:/data/redis
    command: redis-server   /redis.conf   --masterauth $PASSWORD --requirepass $PASSWORD
  master6:
    image: redis:cluster
    networks:
       redis:
         ipv4_address: 172.19.0.7
         aliases:
           - master6
    container_name: master6
    ports:
      - "6373:6379"
    volumes:
      - $PWD/data/redis/master6:/data/redis
    command: redis-server   /redis.conf   --masterauth $PASSWORD --requirepass $PASSWORD
networks:
  redis:
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1
