version: '3'
services:
  master:
      build:
        context: .
        args:
          password: 123456
      image: redis:master
      environment:
        - PASSWORD=123456
      volumes:
        - /data/redis/master:/data/redis
      ports:
        - "6379:6379"
      tty: true
      command: redis-server  --masterauth $PASSWORD --requirepass $PASSWORD
