version: '3'
services:
  master:
      build:
        context: .
        args:
          cluster: "#"   #注解掉集群
      image: redis:master
      environment:
        - PASSWORD=123456
        - TZ=Asia/Shanghai
      volumes:
        - $PWD/data/redis/master:/data/redis
      ports:
        - "6378:6379"
      tty: true
      command: redis-server   /redis.conf   --masterauth $PASSWORD --requirepass $PASSWORD
  slave1:
      image: redis:master
      volumes:
         - $PWD/data/redis/slave1:/data/redis
      environment:
        - PASSWORD=123456
        - TZ=Asia/Shanghai
      depends_on:
          - master
      links:
          - master
      command: redis-server   /redis.conf  --slaveof master 6379 --masterauth $PASSWORD --requirepass $PASSWORD
  slave2:
    image: redis:master
    environment:
      - PASSWORD=123456
      - TZ=Asia/Shanghai
    volumes:
      - $PWD/data/redis/slave2:/data/redis
    depends_on:
      - master
    links:
      - master
    command: redis-server   /redis.conf  --slaveof master 6379 --masterauth $PASSWORD --requirepass $PASSWORD
