version: '3'
services:
  master:
    image: redis:4.0.10-alpine
    command: redis-server --appendonly yes --masterauth $REDIS_PASSWORD --requirepass $REDIS_PASSWORD
    volumes:
      - $PWD/data/master:/data
    ports:
      - "6379:6379"