version: '3.5'
services:
  jenkins:
      build:
        context: .
      image: jenkins:master
      environment:
        - PASSWORD=123456
        - TZ=Asia/Shanghai
      volumes:
        - $PWD/data/jenkins/home:/var/jenkins_home
      ports:
        - "18080:8080"
        - "15000:50000"
      tty: true
      container_name: jenkins
      networks:
        - jenkins
networks:
  tomcats:
    external: false
    name: jenkins