version: '3.5'
services:
  jenkins:
      image: jenkins:2.60.3-alpine
      environment:
        - PASSWORD=123456
        - TZ=Asia/Shanghai
      volumes:
        - $PWD/data/jenkins/home:/var/jenkins_home
      ports:
        - "8082:8080"
        - "50000:50000"
      tty: true
      container_name: jenkins

