version: '3.5'
services:
  es01v6:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.1
    container_name: es01v6
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - TZ=Asia/Shanghai
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      -  $PWD/data/es01v6/:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300 
  skyoap:
    restart: on-failure:3
    image: apache/skywalking-oap-server
    container_name: skyoap
    ports:
      - 11800:11800
    environment:
      - TZ=Asia/Shanghai
      - SW_STORAGE=elasticsearch
      - SW_STORAGE_ES_CLUSTER_NODES=es01v6:9200
    depends_on:
      - es01v6
  skyui:
    image: apache/skywalking-ui
    container_name: skyui
    ports:
      - 8090:8080
    environment:
      - TZ=Asia/Shanghai
      - SW_OAP_ADDRESS=skyoap:12800
    depends_on:
      - skyoap


 