version: '3.5'
services:
  skywalking-oap:
    image: apache/skywalking-oap-server
    container_name: skywalking-oap
    environment:
      - SW_STORAGE=elasticsearch
      - SW_STORAGE_ES_CLUSTER_NODES=elasticsearch:9200
  skywalking-ui:
    image: apache/skywalking-ui
    container_name: skywalking-ui
    environment:
      - SW_OAP_ADDRESS=oap:12800



 