version: '3.5'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
    container_name: es01
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      -  $PWD/data/es01/:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300 
  skywalking-oap:
    image: apache/skywalking-oap-server
    container_name: skywalking-oap
    environment:
      - SW_STORAGE=elasticsearch
      - SW_STORAGE_ES_CLUSTER_NODES=es01:9200
    depends_on:
      - es01
  skywalking-ui:
    image: apache/skywalking-ui
    container_name: skywalking-ui
    ports:
      - 8090:8080
    environment:
      - SW_OAP_ADDRESS=oap:12800
    depends_on:
      - skywalking-oap


 