version: '3.5'
services:
  keepalived:
      build:
        context: .
      image: keepalived:master
      environment:
        - PASSWORD=123456
        - TZ=Asia/Shanghai
      volumes:
        - $PWD/data/keppalived/logs:/data/nginx/logs

      networks:
        - tomcats
      tty: true
      container_name: keppalived
      command:  /bin/sh


      #links:
      #  - tomcat1:t1
      #depends_on:
      #  - tomcat1

networks:
  tomcats:
    external: true
