version: '3.5'
services:
  mq1:
    image: rabbitmq:3.8-rc-management
    container_name: mq1
    #必须指定与节点名字和挂载卷有关
    hostname: mq1
    environment:
      - vm_memory_high_watermark=0.49
      - RABBITMQ_ERLANG_COOKIE="secret cookie here"
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - $PWD/data/rabbitmq/mq1:/var/lib/rabbitmq/mnesia/rabbit@mq1
  mq2:
    image: rabbitmq:3.8-rc-management
    container_name: mq2
    #必须指定与节点名字和挂载卷有关
    hostname: mq2
    environment:
      - vm_memory_high_watermark=0.49
      #集群秘钥
      - RABBITMQ_ERLANG_COOKIE="secret cookie here"
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
      - CLUSTERED=true
      - CLUSTER_WITH=mq1
    ports:
      - "15673:15672"
      - "5673:5672"
    depends_on:
      - "mq1"
    volumes:
      - $PWD/data/rabbitmq/mq2:/var/lib/rabbitmq/mnesia/rabbit@mq2
    command:
      - /bin/sh
      - -c
      - |
         rabbitmq-server
         rabbitmqctl stop_app
         rabbitmqctl reset
         rabbitmqctl join_cluster rabbit@mq1
         rabbitmqctl start_app
  mq3:
    image: rabbitmq:3.8-rc-management
    container_name: mq3
    #必须指定与节点名字和挂载卷有关
    hostname: mq3
    depends_on:
      - "mq1"
    environment:
      - vm_memory_high_watermark=0.49
      - RABBITMQ_ERLANG_COOKIE="secret cookie here"
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
      - CLUSTERED=true
      - CLUSTER_WITH=mq1
    ports:
      - "15674:15672"
      - "5674:5672"
    volumes:
      - $PWD/data/rabbitmq/mq3:/var/lib/rabbitmq/mnesia/rabbit@mq3
    command:
      - /bin/sh
      - -c
      - |
         rabbitmq-server
         rabbitmqctl stop_app
         rabbitmqctl reset
         rabbitmqctl join_cluster rabbit@mq1
         rabbitmqctl start_app