version: '3.5'
x-common:
    &extra_hosts
      extra_hosts:
        - "vm:192.168.239.135"
        - "dev.hpzhan.com:10.253.97.197"
      env_file: a.env
      networks:
        - cloud    
services:
  consul:
      image: consul:latest
      ports:
        - "8500:8500"
      tty: true
      container_name: consul
      hostname: consul
      <<: *extra_hosts
  gate:
      build:
        context: .
      image: jdk:my
      environment:
        - SW_AGENT_NAME=gate
      ports:
        - "8765:8765"
      tty: true
      container_name: gate
      hostname: gate
      <<: *extra_hosts
  front:
      image: jdk:my
      container_name: front
      hostname: front
      tty: true
      environment:
        - SW_AGENT_NAME=front
      <<: *extra_hosts
  admin:
      image: jdk:my
      environment:
        - SW_AGENT_NAME=admin
      tty: true
      container_name: admin
      hostname: admin
      <<: *extra_hosts
  organ:
      image: jdk:my
      environment:
        - SW_AGENT_NAME=admin
      tty: true
      container_name: organ
      hostname: organ
      <<: *extra_hosts
  order:
      image: jdk:my
      environment:
        - SW_AGENT_NAME=order
      tty: true
      container_name: order
      hostname: order
      <<: *extra_hosts
  witness:
      image: jdk:my
      environment:
        - SW_AGENT_NAME=witness
      tty: true
      container_name: witness
      hostname: witness
      <<: *extra_hosts
networks:
  cloud:

 