version: '3.5'
x-common:
    &extra_hosts
      extra_hosts:
      - "vm:192.168.239.135"
      - "dev.hpzhan.com:10.253.97.197"

services:
  consul:
      image: consul:latest
      environment:
        - TZ=Asia/Shanghai
      ports:
        - "8500:8500"
      tty: true
      container_name: consul
      hostname: consul
      networks:
        - cloud  
  gate:
      build:
        context: .
      image: jdk:my
      configs:
         - cloud_config
      environment:
        - SW_AGENT_NAME=gate
      ports:
        - "8765:8765"
      tty: true
      container_name: gate
      hostname: gate
      networks:
        - cloud
      <<: extra_hosts
  front:
      image: jdk:my
      container_name: front
      hostname: front
      tty: true
      environment:
        - SW_AGENT_NAME=front
      extra_hosts:
        - "vm:192.168.239.135"
        - "dev.hpzhan.com:10.253.97.197" 
      networks:
        - cloud
  admin:
      image: jdk:my
      environment:
        - TZ=Asia/Shanghai
      tty: true
      container_name: admin
      hostname: admin
      networks:
        - cloud
  organ:
      image: jdk:my
      environment:
        - TZ=Asia/Shanghai
      tty: true
      container_name: organ
      hostname: organ
      networks:
        - cloud
  order:
      image: jdk:my
      environment:
        - TZ=Asia/Shanghai
      tty: true
      container_name: order
      hostname: order
      networks:
        - cloud
  witness:
      image: jdk:my
      environment:
        - TZ=Asia/Shanghai
      tty: true
      container_name: witness
      hostname: witness
      networks:
        - cloud
networks:
  cloud:

 